### ISSUE TITLE
Calibration function linker errors

### ISSUE THREAD

**Issue by pictographer** [LAtimes2/InternalTemperature#2]
The calibration functions are not declared static and generate linker errors when using them. Making them static appears to fix them. Examples include singlePointCalibrationC, singlePointCalibrationF, dualPointCalibrationC, dualPointCalibrationF, setVTemp25, etc.

**Comment by LAtimes2** [comment]
You are correct. Since a chip has only 1 temperature sensor, I changed the design to be static but forgot to change these functions. I will fix that in the released version this weekend. Thanks.

**Comment by LAtimes2** [comment]
Turns out I really wanted to use a singleton object, but forgot to declare it. Fixed in release 2.1.0.

**Comment by LAtimes2** [comment]
closed
