### ISSUE TITLE
Avoid compiler warning: unused variable 'dummy'

### ISSUE THREAD

**Issue by cabintech** [LAtimes2/InternalTemperature#3]
Line 353 of InternalTemperature.cpp

`int dummy = ADC0_RA;`

produces an 'unused variable' warning when compiled as part of a sketch in a default Arduino IDE setup. It is just a warning, but I prefer clean compilation esp with C/C++ applications. A simple fix would be to add one line to reference the variable in a harmless way:

```
int dummy = ADC0_RA;
(void)(dummy);
```

**Comment by LAtimes2** [comment]
Version 2.1.1 eliminates the compiler warning when compiling for Teensy 3:
(void) ADC0_RA;
